name: ci
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Elm
        uses: jorelali/setup-elm@v2
        with:
          elm-version: 0.19.1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install UglifyJS
        run: npm install -g uglify-js

      - name: Build
        run: |
          pwd
          ls -al
          ./build.sh src/Main.elm

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
